# Generated by Django 6.0.4 on 2026-05-25 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues_app', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrizeDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('first', 'Primer lugar'), ('second', 'Segundo lugar'), ('third', 'Tercer lugar'), ('last', 'Último lugar'), ('global_individual', 'Premio global individual'), ('global_league', 'Premio global por liga')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.CharField(choices=[('league', 'Premio de liga'), ('global', 'Premio global'), ('tie', 'Premio por empate')], default='league', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prize_distributions', to='leagues_app.league')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prize_distributions', to='leagues_app.leaguemember')),
            ],
            options={
                'db_table': 'prize_distributions',
                'ordering': ['league', 'position', '-amount'],
            },
        ),
    ]
