# Generated by Django 6.0.4 on 2026-05-25 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=5, unique=True)),
                ('flag_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('capacity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stadiums',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TournamentStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tournament_stages',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'venues',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GroupCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_countries', to='catalogo.country')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_countries', to='catalogo.group')),
            ],
            options={
                'db_table': 'group_countries',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='countries',
            field=models.ManyToManyField(related_name='groups', through='catalogo.GroupCountry', to='catalogo.country'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateTimeField()),
                ('home_score', models.PositiveIntegerField(blank=True, null=True)),
                ('away_score', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Programado'), ('in_progress', 'En curso'), ('finished', 'Finalizado'), ('cancelled', 'Cancelado')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_matches', to='catalogo.country')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='catalogo.group')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_matches', to='catalogo.country')),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='catalogo.stadium')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='catalogo.tournamentstage')),
            ],
            options={
                'db_table': 'matches',
                'ordering': ['match_date'],
            },
        ),
        migrations.AddField(
            model_name='group',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='catalogo.tournamentstage'),
        ),
        migrations.AddField(
            model_name='stadium',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stadiums', to='catalogo.venue'),
        ),
        migrations.AddConstraint(
            model_name='groupcountry',
            constraint=models.UniqueConstraint(fields=('group', 'country'), name='unique_country_by_group'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('name', 'stage'), name='unique_group_by_stage'),
        ),
    ]
