services:

  db:
    image: postgres:17
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    networks:
      - quiniela_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  backend:
    build:
      context: ../../backend
      dockerfile: ../docker/production/backend/backend.Dockerfile
    env_file:
      - .env
    environment:
      - DEBUG=0
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      db:
        condition: service_healthy
    networks:
      - quiniela_network
    restart: always

  frontend:
    build:
      context: ../../frontend
      dockerfile: ../docker/production/frontend/frontend.Dockerfile
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "80:80"
    depends_on:
      - backend
      - db
    networks:
      - quiniela_network
    restart: always

volumes:
  postgres_prod_data:
  static_volume:
  media_volume:

networks:
  quiniela_network:
    driver: bridge