export const styles = {
  container: {
    minHeight: '100vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'linear-gradient(135deg, #1a472a 0%, #2d5a3d 50%, #1a472a 100%)',
    fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
    position: 'relative',
    overflow: 'hidden',
  },
  // Pseudo elemento para efecto de cancha
  containerBefore: {
    content: '""',
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundImage: 'repeating-linear-gradient(90deg, transparent, transparent 2px, rgba(255,255,255,0.03) 2px, rgba(255,255,255,0.03) 4px)',
    pointerEvents: 'none',
  },
  card: {
    backgroundColor: '#ffffff',
    borderRadius: '16px',
    boxShadow: '0 20px 60px rgba(0, 0, 0, 0.3), inset 0 1px 0 rgba(255, 255, 255, 0.6)',
    padding: '40px',
    width: '100%',
    maxWidth: '450px',
    border: '3px solid #ffd60a',
    position: 'relative',
    zIndex: 1,
  },
  toggleButtons: {
    display: 'flex',
    gap: '10px',
    marginBottom: '30px',
    borderBottom: '3px solid #1a472a',
  },
  toggleButton: {
    flex: 1,
    padding: '14px 16px',
    border: 'none',
    backgroundColor: 'transparent',
    cursor: 'pointer',
    fontSize: '15px',
    fontWeight: '700',
    transition: 'all 0.3s ease',
    borderBottom: '4px solid transparent',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },
  toggleButtonActive: {
    color: '#1a472a',
    borderBottomColor: '#ffd60a',
    backgroundColor: 'rgba(255, 214, 10, 0.1)',
  },
  toggleButtonInactive: {
    color: '#999',
  },
  form: {
    marginTop: '30px',
  },
  formTitle: {
    marginBottom: '25px',
    fontSize: '28px',
    fontWeight: '800',
    color: '#1a472a',
    textAlign: 'center',
    textTransform: 'uppercase',
    letterSpacing: '1px',
  },
  formGroup: {
    marginBottom: '20px',
  },
  label: {
    display: 'block',
    marginBottom: '8px',
    fontSize: '14px',
    fontWeight: '700',
    color: '#1a472a',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },
  input: {
    width: '100%',
    padding: '12px 14px',
    fontSize: '14px',
    border: '2px solid #e0e0e0',
    borderRadius: '8px',
    boxSizing: 'border-box',
    transition: 'all 0.3s ease',
    fontFamily: 'inherit',
  },
  inputFocus: {
    borderColor: '#ffd60a',
    boxShadow: '0 0 8px rgba(255, 214, 10, 0.3)',
    outline: 'none',
  },
  submitButton: {
    width: '100%',
    padding: '14px 16px',
    fontSize: '16px',
    fontWeight: '700',
    color: '#fff',
    backgroundColor: '#1a472a',
    border: '2px solid #1a472a',
    borderRadius: '8px',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    marginTop: '10px',
    textTransform: 'uppercase',
    letterSpacing: '1px',
    boxShadow: '0 4px 15px rgba(26, 71, 42, 0.3)',
  },
  submitButtonHover: {
    backgroundColor: '#ffd60a',
    color: '#1a472a',
    transform: 'translateY(-2px)',
    boxShadow: '0 6px 20px rgba(255, 214, 10, 0.4)',
  },
  submitButtonDisabled: {
    backgroundColor: '#ccc',
    cursor: 'not-allowed',
    boxShadow: 'none',
    transform: 'none',
    border: '2px solid #ccc',
  },
  errorMessage: {
    padding: '14px 16px',
    marginBottom: '20px',
    backgroundColor: '#ffe5e5',
    color: '#c33',
    borderRadius: '8px',
    fontSize: '14px',
    border: '2px solid #ff6b6b',
    fontWeight: '600',
  },
  successMessage: {
    padding: '14px 16px',
    marginBottom: '20px',
    backgroundColor: '#d4edda',
    color: '#155724',
    borderRadius: '8px',
    fontSize: '14px',
    border: '2px solid #28a745',
    fontWeight: '600',
  },
  userInfo: {
    marginBottom: '30px',
    padding: '20px',
    backgroundColor: 'linear-gradient(135deg, rgba(26, 71, 42, 0.05) 0%, rgba(255, 214, 10, 0.05) 100%)',
    borderRadius: '8px',
    border: '2px solid #1a472a',
  },
  infoText: {
    marginBottom: '12px',
    fontSize: '14px',
    color: '#333',
    fontWeight: '500',
  },
  title: {
    marginBottom: '25px',
    fontSize: '32px',
    fontWeight: '800',
    background: 'linear-gradient(135deg, #1a472a 0%, #ffd60a 100%)',
    backgroundClip: 'text',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    textAlign: 'center',
    textTransform: 'uppercase',
    letterSpacing: '1px',
  },
  logoutButton: {
    width: '100%',
    padding: '14px 16px',
    fontSize: '16px',
    fontWeight: '700',
    color: '#fff',
    backgroundColor: '#dc3545',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    textTransform: 'uppercase',
    letterSpacing: '1px',
    boxShadow: '0 4px 15px rgba(220, 53, 69, 0.3)',
  },
  logoutButtonHover: {
    backgroundColor: '#c82333',
    transform: 'translateY(-2px)',
    boxShadow: '0 6px 20px rgba(220, 53, 69, 0.4)',
  },
  switchText: {
    marginTop: '20px',
    textAlign: 'center',
    fontSize: '14px',
    color: '#666',
    fontWeight: '500',
  },
  switchLink: {
    background: 'none',
    border: 'none',
    color: '#1a472a',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: '700',
    textDecoration: 'underline',
    padding: 0,
    transition: 'color 0.3s ease',
  },
  switchLinkHover: {
    color: '#ffd60a',
  },
};
