export const styles = {
  container: {
    minHeight: '100vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'linear-gradient(135deg, #0B1220 0%, #111827 50%, #0B1220 100%)',
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    position: 'relative',
    overflow: 'hidden',
  },
  containerBefore: {
    content: '""',
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundImage: 'repeating-linear-gradient(90deg, transparent, transparent 2px, rgba(255,255,255,0.01) 2px, rgba(255,255,255,0.01) 4px)',
    pointerEvents: 'none',
  },
  card: {
    backgroundColor: '#1F2937',
    borderRadius: '16px',
    boxShadow: '0 25px 50px rgba(0, 0, 0, 0.5), inset 0 1px 0 rgba(255, 255, 255, 0.1)',
    padding: '48px',
    width: '100%',
    maxWidth: '480px',
    border: '1px solid rgba(255, 255, 255, 0.08)',
    position: 'relative',
    zIndex: 1,
    backdropFilter: 'blur(10px)',
  },
  toggleButtons: {
    display: 'flex',
    gap: '12px',
    marginBottom: '32px',
    borderBottom: '1px solid rgba(255, 255, 255, 0.08)',
    paddingBottom: '16px',
  },
  toggleButton: {
    flex: 1,
    padding: '12px 20px',
    border: 'none',
    backgroundColor: 'transparent',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: '600',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    borderBottom: '2px solid transparent',
    color: '#9CA3AF',
    letterSpacing: '0.3px',
  },
  toggleButtonActive: {
    color: '#F9FAFB',
    borderBottomColor: '#2563EB',
    backgroundColor: 'rgba(37, 99, 235, 0.08)',
  },
  toggleButtonInactive: {
    color: '#9CA3AF',
  },
  form: {
    marginTop: '24px',
  },
  formTitle: {
    marginBottom: '28px',
    fontSize: '26px',
    fontWeight: '700',
    color: '#F9FAFB',
    textAlign: 'center',
    letterSpacing: '0.3px',
    background: 'linear-gradient(135deg, #F9FAFB 0%, #D1D5DB 100%)',
    backgroundClip: 'text',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
  },
  formGroup: {
    marginBottom: '24px',
  },
  label: {
    display: 'block',
    marginBottom: '10px',
    fontSize: '13px',
    fontWeight: '600',
    color: '#F9FAFB',
    letterSpacing: '0.2px',
  },
  input: {
    width: '100%',
    padding: '14px 16px',
    fontSize: '14px',
    border: '1px solid rgba(255, 255, 255, 0.1)',
    borderRadius: '10px',
    boxSizing: 'border-box',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    fontFamily: 'inherit',
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    color: '#F9FAFB',
  },
  inputFocus: {
    borderColor: '#2563EB',
    backgroundColor: 'rgba(37, 99, 235, 0.08)',
    boxShadow: '0 0 0 3px rgba(37, 99, 235, 0.1)',
    outline: 'none',
  },
  submitButton: {
    width: '100%',
    padding: '14px 20px',
    fontSize: '15px',
    fontWeight: '600',
    color: '#FFF',
    backgroundColor: '#2563EB',
    border: 'none',
    borderRadius: '10px',
    cursor: 'pointer',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    marginTop: '8px',
    letterSpacing: '0.3px',
    boxShadow: '0 4px 12px rgba(37, 99, 235, 0.3)',
    position: 'relative',
    overflow: 'hidden',
  },
  submitButtonHover: {
    backgroundColor: '#1D4ED8',
    transform: 'translateY(-2px)',
    boxShadow: '0 8px 20px rgba(37, 99, 235, 0.4)',
  },
  submitButtonDisabled: {
    backgroundColor: '#6B7280',
    cursor: 'not-allowed',
    boxShadow: 'none',
    transform: 'none',
    opacity: '0.6',
  },
  errorMessage: {
    padding: '14px 16px',
    marginBottom: '20px',
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
    color: '#FCA5A5',
    borderRadius: '10px',
    fontSize: '14px',
    border: '1px solid rgba(239, 68, 68, 0.3)',
    fontWeight: '500',
  },
  successMessage: {
    padding: '14px 16px',
    marginBottom: '20px',
    backgroundColor: 'rgba(16, 185, 129, 0.1)',
    color: '#6EE7B7',
    borderRadius: '10px',
    fontSize: '14px',
    border: '1px solid rgba(16, 185, 129, 0.3)',
    fontWeight: '500',
  },
  userInfo: {
    marginBottom: '28px',
    padding: '20px',
    backgroundColor: 'rgba(37, 99, 235, 0.08)',
    borderRadius: '12px',
    border: '1px solid rgba(37, 99, 235, 0.2)',
  },
  infoText: {
    marginBottom: '12px',
    fontSize: '14px',
    color: '#D1D5DB',
    fontWeight: '500',
    lineHeight: '1.6',
  },
  title: {
    marginBottom: '28px',
    fontSize: '32px',
    fontWeight: '700',
    background: 'linear-gradient(135deg, #F9FAFB 0%, #60A5FA 100%)',
    backgroundClip: 'text',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    textAlign: 'center',
    letterSpacing: '0.3px',
  },
  logoutButton: {
    width: '100%',
    padding: '14px 20px',
    fontSize: '15px',
    fontWeight: '600',
    color: '#FFF',
    backgroundColor: '#EF4444',
    border: 'none',
    borderRadius: '10px',
    cursor: 'pointer',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    letterSpacing: '0.3px',
    boxShadow: '0 4px 12px rgba(239, 68, 68, 0.3)',
  },
  logoutButtonHover: {
    backgroundColor: '#DC2626',
    transform: 'translateY(-2px)',
    boxShadow: '0 8px 20px rgba(239, 68, 68, 0.4)',
  },
  switchText: {
    marginTop: '20px',
    textAlign: 'center',
    fontSize: '14px',
    color: '#9CA3AF',
    fontWeight: '500',
  },
  switchLink: {
    background: 'none',
    border: 'none',
    color: '#60A5FA',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: '600',
    textDecoration: 'none',
    padding: 0,
    transition: 'all 0.3s ease',
  },
  switchLinkHover: {
    color: '#2563EB',
    textDecoration: 'underline',
  },
};
