# Generated by Django 6.0.4 on 2026-05-29 18:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabla_posiciones', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='away_team',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_team',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='match',
        ),
        migrations.AlterUniqueTogether(
            name='prediction',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='user',
        ),
        migrations.AddIndex(
            model_name='standing',
            index=models.Index(fields=['round_number', 'position'], name='tabla_posic_round_n_1bdc19_idx'),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='Prediction',
        ),
    ]
