# Generated by Django 6.0.4 on 2026-05-29 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues_app', '0004_merge_0002_0003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='league',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='leaguemember',
            options={'ordering': ['-total_points']},
        ),
        migrations.RemoveField(
            model_name='league',
            name='created_at_index',
        ),
    ]
